const encodeId = (id: string) => encodeURIComponent(id);

/** Centralized routes prevent UI code from drifting to unscoped admin APIs. */
export const Routes = Object.freeze({
  appConfig: '/api/app-config',
  auth: {
    sendOtp: '/api/auth/community/send-otp',
    login: '/api/auth/community/login',
    me: '/api/auth/me',
  },
  community: {
    buildings: '/api/community/buildings',
    dashboard: '/api/community/dashboard',
    search: '/api/community/search',
    tickets: '/api/community/tickets',
    visitors: '/api/community/visitors',
    visitorStats: '/api/community/visitors/stats',
    visitorClientOptions: '/api/community/visitors/client-options',
    scanVisitor: '/api/community/visitors/scan',
    members: '/api/community/members',
    meetingBookings: '/api/community/meeting-bookings',
    dayPasses: '/api/community/day-passes',
    dayPassBundles: '/api/community/day-pass-bundles',
    events: '/api/community/events',
    eventCategories: '/api/community/event-categories',
    cabins: '/api/community/cabins',
    meetingRooms: '/api/community/meeting-rooms',
    commonAreas: '/api/community/common-areas',
    clients: '/api/community/building-clients',
    clientResources: '/api/community/clients',
    guests: '/api/community/guests',
    leads: '/api/community/leads',
    rfidCards: '/api/community/rfid-cards',
    printerRequests: '/api/community/printer/requests',
    sendNotification: '/api/community/notifications/send',
  },
  invoices: '/api/invoices',
  zohoCustomerPayment: '/api/payments/zoho-customer-payment',
  extendedHours: {
    requests: '/api/extended-hours/requests',
    effectiveSettings: '/api/extended-hours/settings/effective',
    quote: '/api/extended-hours/quote',
    directRequest: '/api/extended-hours/requests/direct',
  },
  blockableCabins: '/api/cabins',
  discountBundles: '/api/discount-bundles',
  ticketCategories: '/api/ticket-categories',
  staff: '/api/users/staff',
  guestSearch: '/api/leads/guests/search',
  meetingDiscountRequests: '/api/meeting-bookings/discount-requests',
  ticket: (id: string) => `/api/community/tickets/${encodeId(id)}`,
  visitor: (id: string) => `/api/community/visitors/${encodeId(id)}`,
  approveVisitorCheckin: (id: string) => `/api/community/visitors/${encodeId(id)}/approve-checkin`,
  checkinVisitor: (id: string) => `/api/community/visitors/${encodeId(id)}/checkin`,
  checkoutVisitor: (id: string) => `/api/community/visitors/${encodeId(id)}/checkout`,
  event: (id: string) => `/api/community/events/${encodeId(id)}`,
  eventRsvps: (id: string) => `/api/community/events/${encodeId(id)}/rsvps`,
  lead: (id: string) => `/api/community/leads/${encodeId(id)}`,
  leadKyc: (id: string) => `/api/community/leads/${encodeId(id)}/kyc`,
  approveLeadKyc: (id: string) => `/api/community/leads/${encodeId(id)}/kyc/approve`,
  rejectLeadKyc: (id: string) => `/api/community/leads/${encodeId(id)}/kyc/reject`,
  printerRequest: (id: string) => `/api/community/printer/requests/${encodeId(id)}`,
  rfidCard: (id: string) => `/api/community/rfid-cards/${encodeId(id)}`,
  rfidExport: '/api/community/rfid-cards/export',
  rfidImportSample: '/api/community/rfid-cards/import/sample',
  rfidClientImport: '/api/community/rfid-cards/assign-client/import',
  rfidClientImportSample: '/api/community/rfid-cards/assign-client/import/sample',
  clientMembers: (id: string) => `/api/community/clients/${encodeId(id)}/members`,
  clientRfidCards: (id: string) => `/api/community/clients/${encodeId(id)}/rfid-cards`,
  clientRfidExport: (id: string) => `/api/community/clients/${encodeId(id)}/rfid-cards/export`,
  guest: (id: string) => `/api/community/guests/${encodeId(id)}`,
  cabin: (id: string) => `/api/community/cabins/${encodeId(id)}`,
  meetingRoom: (id: string) => `/api/community/meeting-rooms/${encodeId(id)}`,
  commonArea: (id: string) => `/api/community/common-areas/${encodeId(id)}`,
  inventoryImport: (kind: 'cabins' | 'meeting-rooms' | 'common-areas') => `/api/community/${kind}/import`,
  inventoryImportSample: (kind: 'cabins' | 'meeting-rooms' | 'common-areas') => `/api/community/${kind}/import/sample`,
  provisionDayPassAccess: (id: string) => `/api/community/day-passes/${encodeId(id)}/provision-access`,
  meetingRoomSlots: (id: string) => `/api/meeting-rooms/${encodeId(id)}/available-slots`,
  meetingBookingVisitors: (id: string) => `/api/community/meeting-bookings/${encodeId(id)}/visitors`,
  provisionMeetingAccess: (id: string) => `/api/community/meeting-bookings/${encodeId(id)}/provision-access`,
  approveMeetingDiscount: (id: string) => `/api/meeting-bookings/${encodeId(id)}/discount/approve`,
  rejectMeetingDiscount: (id: string) => `/api/meeting-bookings/${encodeId(id)}/discount/reject`,
  matrixUserByPhone: '/api/matrix-users/find-by-phone',
  setMatrixCard: (id: string) => `/api/matrix-users/${encodeId(id)}/set-card-credential`,
  creditsSummary: (clientId: string) => `/api/credits/summary/${encodeId(clientId)}`,
  invoiceUpload: (id: string) => `/api/invoices/${encodeId(id)}/upload-e-invoice`,
  invoicePushZoho: (id: string) => `/api/invoices/${encodeId(id)}/push-zoho`,
  extendedHoursRequest: (id: string, action: 'approval-preview' | 'approve' | 'reject' | 'retry-sync') => `/api/extended-hours/requests/${encodeId(id)}/${action}`,
  blockCabin: (id: string) => `/api/cabins/${encodeId(id)}/block`,
  razorpayCreateOrder: '/api/payments/razorpay/create-order',
  razorpayCreatePaymentLink: '/api/payments/razorpay/create-payment-link',
  razorpaySuccess: '/api/payments/razorpay/success',
});
